### ISSUE TITLE
UIButton的扩展添加到UIControl可好？

### ISSUE THREAD

**Issue by AiweiChujian** [HighwayLaw/HWBlocksUI#2]
加给UIButton还是太局限了，直接给UIControl不好么？

**Comment by AiweiChujian** [comment]
看了下，这种代理转发的方式，对控件和delegate这种一对一的关系是很ok的，但对于UIControl-action-target这种一对多对多的关系，还是过于简单了

**Comment by HighwayLaw** [comment]
> 加给UIButton还是太局限了，直接给UIControl不好么？
嗯，可以考虑的

**Comment by HighwayLaw** [comment]
> 看了下，这种代理转发的方式，对控件和delegate这种一对一的关系是很ok的，但对于UIControl-action-target这种一对多对多的关系，还是过于简单了

UIButton的所有事件已经处理了，无非就是多写一些胶水代码。cocoa设计很奇怪的一点是，在给button添加的事件处理方法中，无法区分是哪个UIControlEvents触发的，所以需要一个事件对应一个selector

**Comment by HighwayLaw** [comment]
> 加给UIButton还是太局限了，直接给UIControl不好么？

最新代码已经支持了
