### ISSUE TITLE
有cocoapods吗？

### ISSUE THREAD

**Issue by yusinan0119** [HighwayLaw/HWBlocksUI#3]
有cocoapods吗？有cocoapods吗？

**Comment by HighwayLaw** [comment]
> 有cocoapods吗？有cocoapods吗？

目前还没，我抽空支持下

**Comment by yusinan0119** [comment]
嗯嗯 抽空再支持一下collecitonView，这类常用的😃 我打算在一个小活儿里试试你这个

**Comment by HighwayLaw** [comment]
> 

好的，😄，已支持pod
